Updating with issues
Emilio-Sakr/WeatherPredictor pull request #10
Opened 2022-05-28 21:05 UTC by Emilio-Sakr

Pull request for #1 #3 #4 #6 #9

2022-06-01 18:23 UTC, AnthonyDTrad commented on .env
> +secret=deff1952d59f883ece260e8683fed21ab0ad9a53323eca4fasdewr344sd
Its a really bad practice to store sensitive config as a plain text. 
See credentials and keyvaults to know more on how to store secrets.

2022-06-01 18:30 UTC, AnthonyDTrad commented on WeatherPredictorApi/SQLApp/crud.py
> +from xmlrpc.client import Boolean
This file is generally called dbContext. The context is the file where you manipulate and work with queries

2022-06-01 18:31 UTC, AnthonyDTrad commented on WeatherPredictorApi/SQLApp/crud.py
> +def hashpassword(user, salt):
Why the class that manipulates the database access should know how to hash a password? is it the db's responsibility?

2022-06-01 18:32 UTC, AnthonyDTrad commented on WeatherPredictorApi/SQLApp/crud.py
> +def dehashpassword(user, data) -> Boolean:
Same here

2022-06-01 18:33 UTC, AnthonyDTrad commented on WeatherPredictorApi/SQLApp/crud.py
> +def getCity(db: Session, name : str):
The goal is to code something that scales. Let's say we add 100 entities after 1 month. We will end up with a huge unmanageable file

2022-06-01 18:35 UTC, AnthonyDTrad commented on WeatherPredictorApi/SQLApp/models.py
> +class city(Base):
Scalable? When we add 100 models. How many lines of code we will have?

2022-06-01 18:39 UTC, AnthonyDTrad commented on WeatherPredictorApi/__init__.py
> +Base.metadata.create_all(bind=engine)
So the API should know that he should drope and recreate the db ?

2022-06-01 18:51 UTC, AnthonyDTrad commented on WeatherPredictorApi/routers/cities.py
> +async def getWeather(city: str, db: Session = Depends(get_db)) -> Dict:
Will need to ask youo about this

2022-06-01 18:52 UTC, AnthonyDTrad requested changes
Got a first look, can you check those comments?

2022-06-02 16:36 UTC, Emilio-Sakr commented
Thank you for your remarks, 
to fix them i'd like to create another branch (updating-with-issues-v2) because I want to restructure the project in better way. i'll disregard this pull request and create another.

2022-06-02 18:10 UTC, closed without merging